### PR TITLE
replace osascript with scutil for vpn disconnect

### PR DESCRIPTION
**Pull request by frodeaa**
no reason to use osascript when scutil support stopping the vpn connection

### CODE REVIEW

**Comment by jonhiggs** [comment]
Cheers. Sorry about the delay, I've been on holiday. I've taken a look at the PR but I'm have some trouble with it not disconnecting. I'm not sure why just yet.

``` ShellSession
$ bash -x vpn disconnect rea-eqx
+ f=disconnect
+ shift
++ echo rea-eqx
++ sed 's#\ #\\\ #g'
+ c=rea-eqx
+ case $f in
+ [[ -z rea-eqx ]]
+ eval 'scutil --nc stop rea-eqx'
++ scutil --nc stop rea-eqx
$ vpn status
rea-eqx             Connected
```

Also, I don't think we need to run scutil through eval anymore either.

I really like the PR too. I didn't notice the scutil supported stopping. That's a much better way to go about it.

**Comment by frodeaa** [comment]
I'm not able to reproduce it, the output for running the same command is however different

    bash -x ./vpn disconnect rea-eqx
    + f=disconnect
    + shift
    ++ echo rea-eqx
    ++ sed 's#\ #\\\ #g'
    + c=rea-eqx
    + case $f in
    + [[ -z rea-eqx ]]
    + eval 'scutil --nc stop '\''rea-eqx'\'''
    ++ scutil --nc stop rea-eqx

so it could be an issue with how the connection parameter is evaluated

**Comment by frodeaa** [comment]
I was not able to reproduce your problem, but the changes in ecb188d may correct it since it changes how connection names are passed to scutil

**Comment by jonhiggs** [comment]
The reason that stop doesn't work seems like it may be a bug in Yosemite. https://discussions.apple.com/thread/6839529?start=0&tstart=0

**Comment by jonhiggs** [comment]
I'm happy to break support for Yosemite now.

**Pull request merged**
